version: '3.8'
services:
  pixiv_vote_bot:
    build: .
    container_name: pixiv_vote_bot
    volumes:
      - ./data:/app/data
      - ./:/app/
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
